### ISSUE TITLE
Is ECCV2020_DiVA_MultiFeature_DML/evaluation/evaluate.py used?

### ISSUE THREAD

**Issue by Wang-Wenqing** [Confusezius/ECCV2020_DiVA_MultiFeature_DML#5]
Hi, I have some confusion about evaluation/evaluate.py, firstly, there is a function (as followed) not defined in this project, while I found this function in another project of yours, and secondly, when I debug it, I found it directly in evaluation/__init__.py and not jump into evaluation/evaluate.py, so is it a mistake putting or I miss something?

https://github.com/Confusezius/ECCV2020_DiVA_MultiFeature_DML/blob/7b9131767a33d67acb19d4753e4b54a5ed0b78b0/evaluation/evaluate.py#L13

https://github.com/Confusezius/ECCV2020_DiVA_MultiFeature_DML/blob/7b9131767a33d67acb19d4753e4b54a5ed0b78b0/evaluation/evaluate.py#L66

**Comment by Confusezius** [comment]
Thanks for pointing that out! `evaluation/evaluate.py` is indeed an obsolete script that is not used; all the evaluation functions are in `evaluation/__init__.py`. I'll remove `evaluation/evaluate.py` to make that clear :).
